-- SYS
--ORCLSTUDY 사용자 권한 취소
GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;
REVOKE RESOURCE, CREATE TABLE FROM ORCLSTUDY;

-- ORCLSTUDY
-- CREATE TABLE하면 오류남
CREATE TABLE temp2(
    no NUMBER
);